

const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCHCHATS";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_REQUEST  = "NEW_REQUEST"
const NEW_MESSAGE ="NEW_MESSAGE"
const START_TYPING ="START_TYPING"
const STOP_TYPING ="STOP_TYPING"
const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEFT = "CHAT_LEFT"
const ONLINE_USERS = "ONLINE_USERS"

export {ALERT ,CHAT_JOINED,CHAT_LEFT,STOP_TYPING,START_TYPING,NEW_MESSAGE, REFETCH_CHATS ,NEW_MESSAGE_ALERT ,NEW_ATTACHEMENT,NEW_REQUEST,ONLINE_USERS}